#!/bin/sh
#deploy="false"
deploy="true"

image=anil
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t jar/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push jar/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag jar/${image}:1.0-SNAPSHOT jar/${image}:latest
        docker push jar/${image}:latest
    fi
fi